FROM php:7.4-apache

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN echo "<Directory /var/www/html/private>"    >> /etc/apache2/apache2.conf && \
    echo "        Require all denied"           >> /etc/apache2/apache2.conf && \
    echo "        Deny from all"                >> /etc/apache2/apache2.conf && \
    echo "</Directory>"                         >> /etc/apache2/apache2.conf

EXPOSE 80
CMD ["apache2-foreground"]
