FROM php:7.4-apache

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install mysqli pdo pdo_mysql

COPY src/ /var/www/html/

RUN echo "<Directory /var/www/html/private>"    >> /etc/apache2/apache2.conf && \
    echo "        Require all denied"           >> /etc/apache2/apache2.conf && \
    echo "        Deny from all"                >> /etc/apache2/apache2.conf && \
    echo "</Directory>"                         >> /etc/apache2/apache2.conf

RUN chmod -R 755 /var/www/html/private/backup
RUN chown -R www-data:www-data /var/www/html/private/backup

EXPOSE 80
CMD ["apache2-foreground"]
